using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace ColorKeyGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ColorKeyGenerator : IIncrementalGenerator
{
    const string Ns = "ColorObject";
    const string Atr = "ColorKeyAttribute";
    const string AtrDisp = $"{Ns}.{Atr}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx => ctx.AddSource("ColorKey.g.cs", PostAtr()));

        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            AtrDisp,
            static (node, token) => node is ClassDeclarationSyntax,
            static (context, token) => context
        );
        context.RegisterSourceOutput(source, Emit);
    }

    static void Emit(SourceProductionContext context, GeneratorAttributeSyntaxContext source)
    {
        var typeSymbol = (INamedTypeSymbol)source.TargetSymbol;
        var typeNode = (TypeDeclarationSyntax)source.TargetNode;
        var className = typeSymbol.Name;

        var accessibility = typeSymbol.DeclaredAccessibility switch
        {
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.Public => "public",
            _ => null,
        };
        if (string.IsNullOrEmpty(accessibility))
        {
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.E0001, typeNode.Identifier.GetLocation(), typeSymbol.Name));
            return;
        }

        if (!typeNode.Modifiers.Any(x => x.IsKind(SyntaxKind.PartialKeyword)))
        {
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.E0002, typeNode.Identifier.GetLocation(), typeSymbol.Name));
            return;
        }

        var sourcePath = source.TargetNode.SyntaxTree.FilePath;
        var unityRoot = sourcePath.Replace(sourcePath.Substring(sourcePath.IndexOf("Assets")), "");
        string? pathRoot = null;
        foreach (var atr in typeSymbol.GetAttributes())
        {
            if (atr?.AttributeClass?.ToDisplayString() == AtrDisp &&
                atr.ConstructorArguments.Length == 1)
            {
                pathRoot = unityRoot + atr.ConstructorArguments[0].Value!.ToString();
            }
        }
        if (string.IsNullOrEmpty(pathRoot) || !Directory.Exists(pathRoot))
        {
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.E0003, typeNode.Identifier.GetLocation(), typeSymbol.Name));
            return;
        }

        var sb = new StringBuilder();
        var sbCode = new StringBuilder();
        foreach (var fp in Directory.GetFiles(pathRoot, "*", SearchOption.AllDirectories))
        {
            if (string.IsNullOrEmpty(fp) || fp.Contains(".meta") || Path.GetExtension(fp) != ".clo") continue;
            var key = Path.GetFileNameWithoutExtension(fp);
            var t = File.ReadAllText(fp);
            var kv = t.Split(':');
            var vs = kv[1].Trim().Split(',');
            if (sb.Length > 0) sb.Append("\n");
            if (sbCode.Length > 0) sbCode.Append("\n");
            switch (kv[0].Trim())
            {
                case "byte":
                    var b1 = vs.Select(x => x.Trim());
                    sb.Append($$"""    public static Color {{key}} => new Color32({{string.Join(", ", b1)}});""");
                    var b2 = vs.Take(3).Select(x => byte.Parse(x.Trim()).ToString("X2"));
                    sbCode.Append($$"""        public const string {{key}} = "#{{string.Join("", b2)}}";""");
                    break;
                case "float":
                    var f1 = vs.Select(x => x.Trim() + "f");
                    sb.Append($$"""    public static Color {{key}} => new Color({{string.Join(", ", f1)}});""");
                    var f2 = vs.Take(3).Select(x => ((byte)(255 * float.Parse(x.Trim()))).ToString("X2"));
                    sbCode.Append($$"""        public const string {{key}} = "#{{string.Join("", f2)}}";""");
                    break;
            }
        }

        var isNamespace = !typeSymbol.ContainingNamespace.IsGlobalNamespace;

        context.AddSource($"{className}.ColorKey.g.cs", $$"""
// <auto-generated/>
using UnityEngine;
{{(isNamespace ? $$"""namespace {{typeSymbol.ContainingNamespace}} {""" : "")}}
{{accessibility}} partial class {{className}}
{
{{sb}}
    public static class Code
    {
{{sbCode}}
    }
}
{{(isNamespace ? "}" : "")}}
""");
    }

    static string PostAtr()
    {
        return $$"""
using System;
namespace {{Ns}}
{
    /// <summary>
    /// keys will be output as 'Color' and 'const string #xxxxxx'.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    internal sealed class {{Atr}} : Attribute
    {
        /// <param name="filePath">relative path starting with 'Assets'</param>
        public {{Atr}}(string filePath) { }
    }
}
""";
    }
}
